# Generated by Django 3.1.2 on 2020-10-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permissionid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
