# Generated by Django 3.1.2 on 2020-11-03 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('dailyeffort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QATicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuename', models.CharField(max_length=50)),
                ('issuedescription', models.CharField(max_length=255)),
                ('video', models.URLField()),
                ('bspstatus', models.BooleanField(default=True)),
                ('approval', models.BooleanField(default=True)),
                ('totaleffort', models.IntegerField()),
                ('review', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstatename', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='externaluser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='workstate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.workstate'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='createdby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='ticketlist',
            field=models.ManyToManyField(blank=True, to='Strix.Ticket'),
        ),
        migrations.AddField(
            model_name='qaticket',
            name='done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='done', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaticket',
            name='initial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='initial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qaticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.ticket'),
        ),
        migrations.AddField(
            model_name='project',
            name='adminid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='adminid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='userlist',
            field=models.ManyToManyField(related_name='userlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developerticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.ticket'),
        ),
        migrations.AddField(
            model_name='developerticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.ticket'),
        ),
    ]
