# Generated by Django 3.1.2 on 2020-11-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0007_auto_20201105_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdby',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.user'),
        ),
    ]
