# Generated by Django 3.1.5 on 2021-03-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0010_auto_20201119_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
