# Generated by Django 3.1.5 on 2021-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0013_auto_20210331_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentmedia',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
