# Generated by Django 3.1.5 on 2021-03-31 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0014_auto_20210331_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentedby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
