# Generated by Django 3.1.5 on 2021-04-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0017_auto_20210401_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='intialstartdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Strix.project'),
        ),
    ]
