# Generated by Django 3.1.5 on 2021-04-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0020_auto_20210401_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprint',
            old_name='intialstartdate',
            new_name='intialenddate',
        ),
    ]
