# Generated by Django 3.1.5 on 2021-04-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Strix', '0022_bugtype_priority_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bugtype',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='severity',
        ),
    ]
